# Generated by Django 5.1.5 on 2025-01-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_last_name_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
